const textForPage1 = [
  "Endüstriyel Sanayi Tesisleri Kurulumu\n Kobinerji, endüstriyel sanayi tesisleri kurulumunda uzmanlaşmıştır. Modern teknoloji ve yüksek mühendislik standartları ile üretim tesislerinizi verimli ve sürdürülebilir bir şekilde inşa ediyoruz Sanayi tesislerinizin maksimum verimlilikle çalışmasını sağlamak için profesyonel çözümler sunuyoruz. *Endüstriyel sanayi tesisleri kurulum* alanında uzman ekibimizle projelerinizi zamanında ve bütçe dostu bir şekilde tamamlıyoruz.",
  "Konut ve Ticari Bina İnşaatı  - 1 resim Konut ve ticari bina inşaatında güvenilir bir ortak arıyorsanızKobinerji doğru adres. Modern yaşam alanları ve iş yerleri için estetik, dayanıklı ve enerji verimli çözümler sunuyoruz. *Konut ve ticari bina inşaatı* hizmetlerimiz, müşterilerimizin beklentilerini aşan projeler ile fark yaratıyor. Yenilikçi tasarımlar ve yüksek kalite standartları ile inşa ettiğimiz binalar, konfor ve işlevselliği bir araya getiriyor.",
  "Alt Yapı ve Üst Yapı İnşaatı - 1 resim Kobinerji, altyapı ve üstyapı inşaat projelerinde kapsamlı hizmetler sunar. Yol, köprü, su ve kanalizasyon sistemleri gibi altyapı projelerinden, kamu binaları ve ticari yapılar gibi üstyapı projelerine kadar geniş bir yelpazede hizmet veriyoruz. *Alt yapı ve üst yapı inşaatı* alanında deneyimli ekibimizle projelerinizi güvenle tamamlıyoruz. Kalite, güvenlik ve sürdürülebilirlik odaklı çözümlerimizle, topluma değer katan yapılar inşa ediyoruz.",
  "Renovasyon ve Restorasyon Hizmetleri - 1 resim Mevcut yapılarınızı modernize etmek veya tarihi binaları restore etmek için profesyonel renovasyon ve restorasyon hizmetlerimizden yararlanın. Kobinerji, estetik ve fonksiyonel iyileştirmeler ile yapılarınızı yeniden hayata döndürüyor.  Renovasyon ve restorasyon hizmetleri kapsamında, enerji verimliliğini artıran çözümler ve modern tasarım yaklaşımları ile binalarınızı geleceğe hazırlıyoruz. Tarihi dokuyu korurken, modern yaşam standartlarını sunuyoruz.",
];

const textForPage2 = [
  "Güneş Enerjisi Santrali (GES) Kurulumu\n Kobinerji, güneş enerjisi santrali (GES) kurulumu konusunda uzmanlaşmış bir mühendislik firmasıdır. ",
  "Çevre dostu ve sürdürülebilir enerji kaynakları kullanarak elektrik üretmenizi sağlıyoruz. *Güneş enerjisi santrali kurulumu* hizmetimiz, en son teknoloji ve yenilikçi çözümlerle, enerji ihtiyaçlarınızı karşılamada güvenilir ve etkili bir yöntem sunar. Projelerinizin tasarımından kurulumuna kadar her aşamada yanınızdayız. #### Hidroelektrik Santral (HES) Kurulumu - 1 resim Hidroelektrik santral (HES) kurulumu, yenilenebilir enerji projelerinizde önemli bir adımdır. Kobinerji, su kaynaklarından enerji elde etmenizi sağlayacak hidroelektrik santrallerinin kurulumu ve işletilmesi konularında geniş bir deneyime sahiptir. *Hidroelektrik santral kurulumu* hizmetimiz ile enerji üretiminde doğaya dost ve ekonomik çözümler sunuyoruz. Projelerinizin her aşamasında profesyonel destek sağlıyoruz.",
];

const arrayOfText = [textForPage1, textForPage2];
//Create array of photos, for each textForPage . photosForPage1
